/**
 * Writes `queries/{highlights,locals,injections}.scm`: JavaScript's queries, then TypeScript's,
 * then EffectScript's (`queries/src`), as one self-contained file each, for editors without
 * TypeScript's queries (ADR-0058), and the Zed extension's copies. `--check` fails when any is
 * out of date.
 */
import * as fs from "node:fs"
import * as path from "node:path"

const root = path.join(import.meta.dirname, "..")
const from = (pkg, file) => path.join(root, "node_modules", pkg, "queries", file)
const parts = {
  "highlights.scm": [
    from("tree-sitter-javascript", "highlights.scm"),
    from("tree-sitter-typescript", "highlights.scm"),
    path.join(root, "queries/src/highlights.scm")
  ],
  "locals.scm": [from("tree-sitter-javascript", "locals.scm"), from("tree-sitter-typescript", "locals.scm")],
  "injections.scm": [from("tree-sitter-javascript", "injections.scm")]
}
const header = (file) =>
  `; GENERATED by scripts/queries.mjs from tree-sitter-javascript, tree-sitter-typescript (MIT) and\n; queries/src/${file}. Edit queries/src, then run node scripts/queries.mjs.\n`
/**
 * Drops `(#is-not? local)`: tree-sitter's CLI knows it, Neovim and Zed don't (Neovim errors on it,
 * Plan 19 review C2). Without it, a local variable named like a global gets the global's colour.
 */
const portable = (query) => query.replace(/\s*\(#is-not\? local\)/g, "")
let stale = []
for (const [file, sources] of Object.entries(parts)) {
  const text = header(file) +
    sources.filter((s) => fs.existsSync(s)).map((s) => `\n; --- ${path.relative(root, s).replaceAll(path.sep, "/").replace(/^node_modules\//, "")}\n\n${portable(fs.readFileSync(s, "utf8")).trim()}\n`).join("")
  // the grammar's queries, and the Zed extension's copies of the ones Zed reads
  const targets = [path.join(root, "queries", file)]
  if (file !== "locals.scm") targets.push(path.join(root, "../zed/languages/effectscript", file))
  for (const target of targets) {
    if (process.argv.includes("--check")) {
      if (!fs.existsSync(target) || fs.readFileSync(target, "utf8") !== text) stale.push(path.relative(root, target))
    } else fs.writeFileSync(target, text)
  }
}
/**
 * A query's top-level patterns, each with its captures, quantifiers and predicates: Helix lets the
 * first matching pattern win where Neovim and Zed let the last one win, so its copy is the same
 * patterns in reverse (Plan 19 review I3).
 */
const patterns = (query) => {
  const out = []
  let depth = 0
  let current = ""
  for (let i = 0; i < query.length; i++) {
    const c = query[i]
    if (c === ";") {
      // a comment runs to the end of the line
      const end = query.indexOf("\n", i)
      i = end === -1 ? query.length : end
      continue
    }
    const startsForm = depth === 0 && (c === "(" || c === "[" || c === "\"")
    if (startsForm && current.trim() !== "" && !/^[@*+?!]/.test(query.slice(i).trimStart())) {
      out.push(current.trim())
      current = ""
    }
    if (c === "\"") {
      // a string, with escapes
      let j = i + 1
      while (j < query.length && query[j] !== "\"") j += query[j] === "\\" ? 2 : 1
      current += query.slice(i, j + 1)
      i = j
      continue
    }
    if (c === "(" || c === "[") depth++
    if (c === ")" || c === "]") depth--
    current += c
  }
  if (current.trim() !== "") out.push(current.trim())
  return out
}
const helix = path.join(root, "queries/helix/highlights.scm")
const helixText = `; GENERATED by scripts/queries.mjs for Helix: queries/highlights.scm's patterns in reverse order,\n; because in Helix the first matching pattern wins.\n\n${
  patterns(fs.readFileSync(path.join(root, "queries/highlights.scm"), "utf8")).reverse().join("\n\n")
}\n`
if (process.argv.includes("--check")) {
  if (!fs.existsSync(helix) || fs.readFileSync(helix, "utf8") !== helixText) stale.push("queries/helix/highlights.scm")
} else {
  fs.mkdirSync(path.dirname(helix), { recursive: true })
  fs.writeFileSync(helix, helixText)
}
if (stale.length > 0) {
  process.stderr.write(`queries out of date: ${stale.join(", ")}; run node scripts/queries.mjs\n`)
  process.exitCode = 1
}
