/**
 * Writes `queries/{highlights,locals,injections}.scm`: JavaScript's queries, then TypeScript's,
 * then EffectScript's (`queries/src`), as one self-contained file each, for editors without
 * TypeScript's queries (ADR-0058). `--check` fails when they are out of date.
 */
import * as fs from "node:fs"
import * as path from "node:path"

const root = path.join(import.meta.dirname, "..")
const from = (pkg, file) => path.join(root, "node_modules", pkg, "queries", file)
const parts = {
  "highlights.scm": [
    from("tree-sitter-javascript", "highlights.scm"),
    from("tree-sitter-typescript", "highlights.scm"),
    path.join(root, "queries/src/highlights.scm")
  ],
  "locals.scm": [from("tree-sitter-javascript", "locals.scm"), from("tree-sitter-typescript", "locals.scm")],
  "injections.scm": [from("tree-sitter-javascript", "injections.scm")]
}
const header = (file) =>
  `; GENERATED by scripts/queries.mjs from tree-sitter-javascript, tree-sitter-typescript (MIT) and\n; queries/src/${file}. Edit queries/src, then run node scripts/queries.mjs.\n`
let stale = []
for (const [file, sources] of Object.entries(parts)) {
  const text = header(file) +
    sources.filter((s) => fs.existsSync(s)).map((s) => `\n; --- ${path.relative(root, s).replaceAll(path.sep, "/").replace(/^node_modules\//, "")}\n\n${fs.readFileSync(s, "utf8").trim()}\n`).join("")
  const target = path.join(root, "queries", file)
  if (process.argv.includes("--check")) {
    if (!fs.existsSync(target) || fs.readFileSync(target, "utf8") !== text) stale.push(file)
  } else fs.writeFileSync(target, text)
}
if (stale.length > 0) {
  process.stderr.write(`queries out of date: ${stale.join(", ")}; run node scripts/queries.mjs\n`)
  process.exitCode = 1
}
