/**
 * `pnpm codegen` for the dogfooded CLI (ADR-0032): compiles `src/cli/*.efx` into checked-in,
 * dprint-formatted `src/cli/*.ts`. With `--check`, reports stale files instead (exit 1).
 */
import { spawnSync } from "node:child_process"
import * as fs from "node:fs"
import * as path from "node:path"
import { formatDiagnostic, toTypeScript } from "../src/compiler/index.ts"

const root = path.join(import.meta.dirname, "..")
const cli = path.join(root, "src/cli")
const check = process.argv.includes("--check")
let failed = false

for (const file of fs.readdirSync(cli).filter((f) => f.endsWith(".efx"))) {
  const source = fs.readFileSync(path.join(cli, file), "utf8")
  const result = toTypeScript(source, { filename: `src/cli/${file}`, rewriteImportExtensions: "ts" })
  const errors = result.diagnostics.filter((d) => d.severity === "error")
  for (const d of errors) process.stderr.write(`${formatDiagnostic(source, `src/cli/${file}`, d)}\n`)
  if (errors.length > 0) {
    failed = true
    continue
  }
  const out = file.replace(/\.efx$/, ".ts")
  const header =
    `// GENERATED by scripts/compile-cli.ts from ${file}. Do not edit: change the .efx and run pnpm codegen.\n`
  const formatted = spawnSync("pnpm", ["exec", "dprint", "fmt", "--stdin", `src/cli/${out}`], {
    input: `${header}${result.code}`,
    encoding: "utf8",
    cwd: root
  })
  if (formatted.status !== 0) {
    process.stderr.write(formatted.stderr)
    failed = true
    continue
  }
  const target = path.join(cli, out)
  if (!check) fs.writeFileSync(target, formatted.stdout)
  else if (!fs.existsSync(target) || fs.readFileSync(target, "utf8") !== formatted.stdout) {
    process.stderr.write(`src/cli/${out} is stale: run pnpm codegen\n`)
    failed = true
  }
}
process.exitCode = failed ? 1 : 0
