/**
 * The Homebrew formula for the `EffectScript-Lang/homebrew-tap` tap (ADR-0036, ADR-0038):
 *
 *   node scripts/homebrew.ts --version <version> --shasums dist-bin/SHASUMS256.txt > Formula/effectscript.rb
 *
 * `--base <url>` replaces the release download folder (for scripts/xplatform.sh).
 * Homebrew runs on macOS and glibc Linux, so the formula pins those four builds.
 */
import * as fs from "node:fs"

const releases = "https://github.com/EffectScript-Lang/effect-lang/releases/download"

const option = (name: string): string | undefined => {
  const i = process.argv.indexOf(name)
  return i === -1 ? undefined : process.argv[i + 1]
}

const formula = (version: string, sums: ReadonlyMap<string, string>, base: string): string => {
  const asset = (target: string) => {
    const file = `efx-${target}.tar.gz`
    const sha = sums.get(file)
    if (sha === undefined) throw new Error(`SHASUMS256.txt has no checksum for ${file}`)
    return `      url "${base}/${file}"\n      sha256 "${sha}"`
  }
  return `# GENERATED by packages/effectscript/core/scripts/homebrew.ts in EffectScript-Lang/effect-lang.
class Effectscript < Formula
  desc "TypeScript with Effect as native syntax"
  homepage "https://effectscript.dev"
  version "${version}"
  license "MIT"

  on_macos do
    on_arm do
${asset("darwin-arm64")}
    end
    on_intel do
${asset("darwin-x64")}
    end
  end

  on_linux do
    on_arm do
${asset("linux-arm64")}
    end
    on_intel do
${asset("linux-x64")}
    end
  end

  def install
    bin.install "efx"
  end

  def caveats
    <<~EOS
      Start using EffectScript in a project:
        efx init      # editor plugin and scripts
        efx convert   # convert the project's TypeScript (on a new git branch)
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/efx --version")
    (testpath/"hello.efx").write("const n: number = 40 + 2\\nconsole.log(n)\\n")
    assert_equal "42", shell_output("#{bin}/efx run hello.efx").strip
  end
end
`
}

try {
  const version = option("--version")
  const shasums = option("--shasums")
  if (version === undefined || shasums === undefined) {
    throw new Error("usage: node scripts/homebrew.ts --version <version> --shasums <SHASUMS256.txt>")
  }
  const sums = new Map(
    fs.readFileSync(shasums, "utf8").split("\n").flatMap((line) => {
      const [sha, file] = line.trim().split(/\s+/)
      return sha !== undefined && file !== undefined ? [[file, sha] as const] : []
    })
  )
  process.stdout.write(formula(version, sums, option("--base") ?? `${releases}/effectscript@${version}`))
} catch (error) {
  process.stderr.write(`${(error as Error).message}\n`)
  process.exitCode = 1
}
