; GENERATED by scripts/queries.mjs from tree-sitter-javascript, tree-sitter-typescript (MIT) and
; queries/src/locals.scm. Edit queries/src, then run node scripts/queries.mjs.

; --- tree-sitter-javascript/queries/locals.scm

; Scopes
;-------

[
  (statement_block)
  (function_expression)
  (arrow_function)
  (function_declaration)
  (method_definition)
] @local.scope

; Definitions
;------------

(pattern/identifier) @local.definition

(variable_declarator
  name: (identifier) @local.definition)

; References
;------------

(identifier) @local.reference

; --- tree-sitter-typescript/queries/locals.scm

(required_parameter (identifier) @local.definition)
(optional_parameter (identifier) @local.definition)
