// GENERATED by scripts/compile-cli.ts from main.efx. Do not edit: change the .efx and run pnpm codegen.
import { NodeRuntime, NodeServices } from "@effect/platform-node"
// @efx no-ambient
/**
 * The `efx` command (spec §7.1): EffectScript command modules on `effect/cli`, compiled by
 * `pnpm codegen` into `main.ts` (ADR-0032).
 *
 * @since 4.0.0
 */
import { Effect, pipe, Runtime, Schema } from "effect"
import { Argument, Command, Flag } from "effect/cli"
import { convertProject } from "../convert/project.ts"
import { check as checkProject } from "./check.ts"
import { docsProject } from "./docs.ts"
import { doctor as checkSetup } from "./doctor.ts"
import { initProject } from "./init.ts"
import { lsp as runLanguageServer } from "./lsp.ts"
import { buildProject, passthrough, printFile, version } from "./project.ts"
import { run as runFile } from "./run.ts"

/** A command's exit code: `runMain` exits with it, without logging (Runtime.errorExitCode). */
export class ExitCode extends Schema.TaggedError<ExitCode>()("ExitCode", {
  code: Schema.Number
}) {
  override get [Runtime.errorExitCode]() {
    return this.code
  }
  override get [Runtime.errorReported]() {
    return false
  }
}

/** Fails with the exit code unless it is 0. */
const exitWith = Effect.fnUntraced(function*(code: number) {
  if (code !== 0) return yield* new ExitCode({ code })
})

/** Compile .efx files to JavaScript and declarations */
export const build = Command.make(
  "build",
  {
    project: Flag.String("project").pipe(
      Flag.withDefault("tsconfig.json"),
      Flag.withAlias("p"),
      Flag.withDescription("The tsconfig.json to build")
    )
  },
  Effect.fn("build")(function*({ project }) {
    yield* exitWith(yield* Effect.promise(() => buildProject(project)))
  })
).pipe(Command.withDescription("Compile .efx files to JavaScript and declarations"))

/** Print a file converted to TypeScript or EffectScript */
export const print = Command.make(
  "print",
  {
    file: Argument.String("file").pipe(Argument.withDescription("The file to convert")),
    to: Flag.Literals("to", ["ts", "efx"]).pipe(
      Flag.optional,
      Flag.withDescription("What to print: ts or efx (default: the other language)")
    )
  },
  Effect.fn("print")(function*({ file, to }) {
    const printed = printFile(file, to._tag === "Some" ? to.value : undefined)
    process.stdout.write(printed.output)
    for (const message of printed.messages) process.stderr.write(`${message}\n`)
    yield* exitWith(printed.ok ? 0 : 1)
  })
).pipe(Command.withDescription("Print a file converted to TypeScript or EffectScript"))

// `check` and `run` forward arguments after `--`: the `command` construct has no variadic form yet

/** Type-check the project, .efx files included */
export const check = pipe(
  Command.make(
    "check",
    {
      project: Flag.String("project").pipe(
        Flag.withAlias("p"),
        Flag.optional,
        Flag.withDescription("The tsconfig.json to check")
      ),
      args: Argument.String("args").pipe(Argument.variadic(), Argument.withDescription("More tsc arguments (after --)"))
    },
    Effect.fnUntraced(function*({ project, args }) {
      const projectArgs = project._tag === "Some" ? ["-p", project.value] : []
      yield* exitWith(checkProject([...projectArgs, ...args]))
    })
  ),
  Command.withDescription("Type-check the project, .efx files included")
)

/** Run a .efx or .ts file */
export const run = pipe(
  Command.make(
    "run",
    {
      runtime: Flag.Literals("runtime", ["node", "bun"]).pipe(
        Flag.optional,
        Flag.withDescription("node or bun (default: bun when the project has @effect/platform-bun)")
      ),
      file: Argument.String("file").pipe(Argument.withDescription("The entry file")),
      args: Argument.String("args").pipe(Argument.variadic(), Argument.withDescription("Arguments for the program"))
    },
    Effect.fnUntraced(function*({ runtime, file, args }) {
      yield* exitWith(runFile([file, ...args], runtime._tag === "Some" ? runtime.value : undefined))
    })
  ),
  Command.withDescription("Run a .efx or .ts file")
)

/** Convert TypeScript files with Effect to EffectScript (spec §7.5) */
export const convert = pipe(
  Command.make(
    "convert",
    {
      paths: Argument.String("paths").pipe(
        Argument.variadic(),
        Argument.withDescription("Files or directories (default: the whole project)")
      ),
      write: Flag.Boolean("write").pipe(
        Flag.withDefault(false),
        Flag.withDescription("Convert on a new branch, effectscript/convert (default: only report)")
      ),
      explain: Flag.Boolean("explain").pipe(
        Flag.withDefault(false),
        Flag.withDescription("Show what stays TypeScript, and why")
      ),
      force: Flag.Boolean("force").pipe(Flag.withDefault(false), Flag.withDescription("Allow uncommitted changes")),
      noVerify: Flag.Boolean("no-verify").pipe(
        Flag.withDefault(false),
        Flag.withDescription("Skip efx check and the tests after converting")
      ),
      test: Flag.String("test").pipe(
        Flag.optional,
        Flag.withDescription("The test command (default: npm test, when there is a test script)")
      )
    },
    Effect.fnUntraced(function*({ paths, write, explain, force, noVerify, test }) {
      const code = convertProject(process.cwd(), {
        paths,
        write,
        explain,
        force,
        verify: !noVerify,
        test: test._tag === "Some" ? test.value : undefined
      }, {
        out: (line) => process.stdout.write(`${line}\n`),
        err: (line) => process.stderr.write(`${line}\n`)
      })
      yield* exitWith(code)
    })
  ),
  Command.withDescription("Convert TypeScript files with Effect to EffectScript")
)

/** Generate API docs (Markdown for Blume) from doc comments (docs spec §3) */
export const docs = pipe(
  Command.make(
    "docs",
    {
      paths: Argument.String("paths").pipe(
        Argument.variadic(),
        Argument.withDescription("Files or directories (default: src)")
      ),
      out: Flag.String("out").pipe(
        Flag.withDefault("docs/api"),
        Flag.withDescription("Where to write the pages (replaced on each run)")
      ),
      check: Flag.Boolean("check").pipe(
        Flag.withDefault(false),
        Flag.withDescription("Only report problems; write nothing")
      ),
      strict: Flag.Boolean("strict").pipe(
        Flag.withDefault(false),
        Flag.withDescription("Fail on warnings, and flag tags that repeat the signature")
      )
    },
    Effect.fnUntraced(function*({ paths, out, check, strict }) {
      yield* exitWith(docsProject(process.cwd(), { paths, out, check, strict }, {
        out: (line) => process.stdout.write(`${line}\n`),
        err: (line) => process.stderr.write(`${line}\n`)
      }))
    })
  ),
  Command.withDescription("Generate API docs from doc comments")
)

/** Set up this project for EffectScript */
export const init = Command.make(
  "init",
  {},
  Effect.fn("init")(function*() {
    yield* exitWith(initProject(process.cwd(), (line) => process.stdout.write(`${line}\n`)))
  })
).pipe(Command.withDescription("Set up this project for EffectScript"))

/** Report what is installed and configured for EffectScript, and what is missing */
export const doctor = Command.make(
  "doctor",
  {},
  Effect.fn("doctor")(function*() {
    yield* exitWith(checkSetup(process.cwd(), (line) => process.stdout.write(`${line}\n`)))
  })
).pipe(Command.withDescription("Report what is installed and configured for EffectScript, and what is missing"))

/** Run the EffectScript language server (for Neovim, Helix, Zed and other LSP editors) */
export const lsp = pipe(
  Command.make(
    "lsp",
    {
      stdio: Flag.Boolean("stdio").pipe(
        Flag.withDefault(true),
        Flag.withDescription("Talk LSP over stdin and stdout (the default)")
      )
    },
    Effect.fnUntraced(function*() {
      yield* exitWith(runLanguageServer(process.cwd()))
    })
  ),
  Command.withDescription("Run the EffectScript language server over stdio")
)

export const efx = pipe(
  Command.make("efx"),
  Command.withDescription("EffectScript: TypeScript with Effect as native syntax"),
  Command.withSubcommands([build, check, run, print, convert, docs, init, doctor, lsp])
)

NodeRuntime.runMain(
  Effect.gen(function*() {
    // without a command, show the help; `run`/`check` pass their arguments through (ADR-0033)
    const argv = process.argv.slice(2)
    yield* Command.runWith(efx, { version })(argv.length === 0 ? ["--help"] : passthrough(argv))
  }).pipe(Effect.provide(NodeServices.layer))
)
