// GENERATED by scripts/compile-cli.ts from main.efx. Do not edit: change the .efx and run pnpm codegen.
import { NodeRuntime, NodeServices } from "@effect/platform-node"
// @efx no-ambient
/**
 * The `efx` command (spec §7.1): EffectScript command modules on `effect/cli`, compiled by
 * `pnpm codegen` into `main.ts` (ADR-0032).
 *
 * @since 4.0.0
 */
import { Effect, pipe, Runtime, Schema } from "effect"
import { Argument, Command, Flag } from "effect/cli"
import { check as checkProject } from "./check.ts"
import { buildProject, version } from "./project.ts"
import { run as runFile } from "./run.ts"

/** A command's exit code: `runMain` exits with it, without logging (Runtime.errorExitCode). */
export class ExitCode extends Schema.TaggedError<ExitCode>()("ExitCode", {
  code: Schema.Number
}) {
  override get [Runtime.errorExitCode]() {
    return this.code
  }
  override get [Runtime.errorReported]() {
    return false
  }
}

/** Fails with the exit code unless it is 0. */
const exitWith = Effect.fnUntraced(function*(code: number) {
  if (code !== 0) return yield* new ExitCode({ code })
})

/** Compile .efx files to JavaScript and declarations */
export const build = Command.make(
  "build",
  {
    project: Flag.String("project").pipe(
      Flag.withDefault("tsconfig.json"),
      Flag.withAlias("p"),
      Flag.withDescription("The tsconfig.json to build")
    )
  },
  Effect.fn("build")(function*({ project }) {
    yield* exitWith(yield* Effect.promise(() => buildProject(project)))
  })
).pipe(Command.withDescription("Compile .efx files to JavaScript and declarations"))

// `check` and `run` forward arguments after `--`: the `command` construct has no variadic form yet

/** Type-check the project, .efx files included */
export const check = pipe(
  Command.make(
    "check",
    {
      project: Flag.String("project").pipe(
        Flag.withAlias("p"),
        Flag.optional,
        Flag.withDescription("The tsconfig.json to check")
      ),
      args: Argument.String("args").pipe(Argument.variadic(), Argument.withDescription("More tsc arguments (after --)"))
    },
    Effect.fnUntraced(function*({ project, args }) {
      const projectArgs = project._tag === "Some" ? ["-p", project.value] : []
      yield* exitWith(checkProject([...projectArgs, ...args]))
    })
  ),
  Command.withDescription("Type-check the project, .efx files included")
)

/** Run a .efx or .ts file */
export const run = pipe(
  Command.make(
    "run",
    {
      file: Argument.String("file").pipe(Argument.withDescription("The entry file")),
      args: Argument.String("args").pipe(
        Argument.variadic(),
        Argument.withDescription("Arguments for the program (after --)")
      )
    },
    Effect.fnUntraced(function*({ file, args }) {
      yield* exitWith(runFile([file, ...args]))
    })
  ),
  Command.withDescription("Run a .efx or .ts file")
)

export const efx = pipe(
  Command.make("efx"),
  Command.withDescription("EffectScript: TypeScript with Effect as native syntax"),
  Command.withSubcommands([build, check, run])
)

NodeRuntime.runMain(
  Effect.gen(function*() {
    // without a command, show the help
    const argv = process.argv.slice(2)
    yield* Command.runWith(efx, { version })(argv.length === 0 ? ["--help"] : argv)
  }).pipe(Effect.provide(NodeServices.layer))
)
