; GENERATED by scripts/queries.mjs for Helix: queries/highlights.scm's patterns in reverse order,
; because in Helix the first matching pattern wins.

(route
  method: (identifier) @keyword
  name: (identifier) @function.method
  path: (string) @string.special)

(flag_parameter
  name: (identifier) @variable.parameter)

(service_property
  name: (property_identifier) @property)

(schema_field
  name: (property_identifier) @property)

(api_declaration
  name: (identifier) @type)

(group_declaration
  name: (identifier) @type)

(service_declaration
  name: (identifier) @type)

(config_declaration
  name: (identifier) @type)

(error_declaration
  name: (identifier) @type)

(schema_variant
  name: (identifier) @type)

(schema_declaration
  name: (identifier) @type)

(command_declaration
  name: (identifier) @function)

(effect_method_signature
  name: (property_identifier) @function.method)

(effect_method
  name: (property_identifier) @function.method)

(effect_declaration
  name: (identifier) @function)

(flag_parameter "--" @operator)

(topic_reference) @variable.builtin

"|>" @operator

(match_arm "default" @keyword)

[
  "effect"
  "schema"
  "error"
  "service"
  "layer"
  "config"
  "atom"
  "group"
  "api"
  "command"
  "test"
  "describe"
  "doctest"
  "impl"
  "main"
  "defer"
  "throws"
  "needs"
  "match"
  "when"
  "middleware"
  "status"
  "rpc"
] @keyword

[ "abstract"
  "declare"
  "enum"
  "export"
  "implements"
  "interface"
  "keyof"
  "namespace"
  "private"
  "protected"
  "public"
  "type"
  "readonly"
  "override"
  "satisfies"
] @keyword

(optional_parameter (identifier) @variable.parameter)

(required_parameter (identifier) @variable.parameter)

(type_arguments
  "<" @punctuation.bracket
  ">" @punctuation.bracket)

((identifier) @type
 (#match? @type "^[A-Z]"))

(predefined_type) @type.builtin

(type_identifier) @type

[
  "as"
  "async"
  "await"
  "break"
  "case"
  "catch"
  "class"
  "const"
  "continue"
  "debugger"
  "default"
  "delete"
  "do"
  "else"
  "export"
  "extends"
  "finally"
  "for"
  "from"
  "function"
  "get"
  "if"
  "import"
  "in"
  "instanceof"
  "let"
  "new"
  "of"
  "return"
  "set"
  "static"
  "switch"
  "target"
  "throw"
  "try"
  "typeof"
  "var"
  "void"
  "while"
  "with"
  "yield"
] @keyword

(template_substitution
  "${" @punctuation.special
  "}" @punctuation.special) @embedded

[
  "("
  ")"
  "["
  "]"
  "{"
  "}"
]  @punctuation.bracket

[
  "-"
  "--"
  "-="
  "+"
  "++"
  "+="
  "*"
  "*="
  "**"
  "**="
  "/"
  "/="
  "%"
  "%="
  "<"
  "<="
  "<<"
  "<<="
  "="
  "=="
  "==="
  "!"
  "!="
  "!=="
  "=>"
  ">"
  ">="
  ">>"
  ">>="
  ">>>"
  ">>>="
  "~"
  "^"
  "&"
  "|"
  "^="
  "&="
  "|="
  "&&"
  "||"
  "??"
  "&&="
  "||="
  "??="
] @operator

[
  ";"
  (optional_chain)
  "."
  ","
] @punctuation.delimiter

(number) @number

(regex) @string.special

[
  (string)
  (template_string)
] @string

(comment) @comment

[
  (true)
  (false)
  (null)
  (undefined)
] @constant.builtin

(super) @variable.builtin

(this) @variable.builtin

((identifier) @function.builtin
 (#eq? @function.builtin "require"))

((identifier) @variable.builtin
 (#match? @variable.builtin "^(arguments|module|console|window|document)$"))

([
    (identifier)
    (shorthand_property_identifier)
    (shorthand_property_identifier_pattern)
 ] @constant
 (#match? @constant "^[A-Z_][A-Z\\d_]+$"))

((identifier) @constructor
 (#match? @constructor "^[A-Z]"))

(call_expression
  function: (member_expression
    property: (property_identifier) @function.method))

(call_expression
  function: (identifier) @function)

(assignment_expression
  left: (identifier) @function
  right: [(function_expression) (arrow_function)])

(variable_declarator
  name: (identifier) @function
  value: [(function_expression) (arrow_function)])

(assignment_expression
  left: (member_expression
    property: (property_identifier) @function.method)
  right: [(function_expression) (arrow_function)])

(pair
  key: (property_identifier) @function.method
  value: [(function_expression) (arrow_function)])

(method_definition
  name: (property_identifier) @function.method)

(function_declaration
  name: (identifier) @function)

(function_expression
  name: (identifier) @function)

(property_identifier) @property

(identifier) @variable
